"""Generates Dockerfile and fly.toml for service deployment."""

from __future__ import annotations

from neurohub_sdk.base import BaseService


def generate_dockerfile(service: BaseService) -> str:
    """Generate a Dockerfile for the service container."""
    return f"""\
# Auto-generated by neurohub-sdk for {service.config.name}:{service.config.version}
FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \\
    PYTHONUNBUFFERED=1

WORKDIR /app

# Install system dependencies (add custom deps in requirements.txt)
RUN apt-get update \\
    && apt-get install -y --no-install-recommends curl \\
    && rm -rf /var/lib/apt/lists/*

# Install neurohub-sdk and service dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir neurohub-sdk -r requirements.txt

# Copy service code
COPY . .

EXPOSE 8080

HEALTHCHECK --interval=15s --timeout=5s --retries=3 \\
    CMD curl -f http://localhost:8080/health || exit 1

CMD ["python", "-m", "service"]
"""


def generate_fly_toml(service: BaseService, app_name: str, region: str = "nrt") -> str:
    """Generate fly.toml for Fly.io deployment."""
    return f"""\
# Auto-generated by neurohub-sdk for {service.config.name}:{service.config.version}
app = "{app_name}"
primary_region = "{region}"

[build]
  dockerfile = "Dockerfile"

[env]
  NEUROHUB_SERVICE_NAME = "{service.config.name}"
  NEUROHUB_SERVICE_VERSION = "{service.config.version}"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = "requests"
    hard_limit = 50
    soft_limit = 25

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[checks]
  [checks.health]
    port = 8080
    type = "http"
    method = "GET"
    path = "/health"
    interval = "15s"
    timeout = "5s"
    grace_period = "10s"
"""
